dist : focal fossa
language: python
python:
  - '3.8'

addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable

branches:
  only:
    - staging

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
CHROME_DRIVER_VERSION=`curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
unzip ~/chromedriver_linux64.zip -d ~/
rm ~/chromedriver_linux64.zip
sudo mv -f ~/chromedriver /usr/local/bin/chromedriver

env: DJANGO_SETTINGS_MODULE="purbeurre_project.settings.ci"

services:
  - postgresql

script:
  - coverage run --source="." ./manage.py test purbeurre_project/apps/

after_success:
  - cd purbeurre_project/
  - pytest -vv